### ISSUE TITLE
Issues with release

### ISSUE THREAD

**Issue by cameronezell** [alexa-samples/alexa-video-multimodal#2]
I am having issues after running `npm run release` from the lambda folder. The error below is the output on Windows, but I'm also having the same problems from Mac. Node is version 10.18.1 and npm is on 6.13.4.
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'c:\Users\xxxx\Documents\Dev\alexa-video-multimodal\lambda\node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by cameronezell** [comment]
BTW I downgraded npm to version 6.11.3 after I posted this after seeing that requirement, but it resulted in the same errors.

**Comment by cameronezell** [comment]
I tried deploying this unsuccessfully from Mac OS 10.13, 10.15, and Windows 10. I was finally able to make this work only on MacOS 10.14, I'm not sure why that is.

**Comment by tuckefre** [comment]
Thank you for telling us about this issue. A member of the team will be working on it and will provide updates here about progress.

**Comment by tuckefre** [comment]
There are special steps required for installing and using this toolkit on Windows as defined in the documentation here: https://developer.amazon.com/docs/video-skills-multimodal-devices/sample-video-skill-overview.html#other-dependencies

In summary the installation steps should be:
* Clone the Git repository
* Install NodeJs
* Run this command for Windows build tools: `npm install --global --production windows-build-tools`
* Install Visual Studio Build Tools (https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools)
* Install the CLI tool by navigating to the directory `./infrastructure` and running the command `npm run release`
* The remaining steps for creating and managing skills should be the same regardless of OS

For a fresh install, ensure the following files and directories are removed before running `npm run release`:
* `./infrastructure/node_modules`
* `./infrastructure/dist`
* `./infrastructure/package-lock.json`
* `./lambda/node_modules`
* `./lambda/dist`
* `./lambda/package-lock.json`
* `./web-player/node_modules`
* `./web-player/dist`
* `./web-player/package-lock.json`
